-- CreateTable
CREATE TABLE "_migration_internal_statements" (
    "statement_order" INT8 NOT NULL,
    "statement_id" UUID NOT NULL,
    "data" JSONB,

    CONSTRAINT "_migration_internal_statements_pkey" PRIMARY KEY ("statement_order")
);

-- CreateTable
CREATE TABLE "customer" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING(255) NOT NULL,
    "address" STRING(255) NOT NULL,
    "email" STRING(50),
    "gender" STRING(20),

    CONSTRAINT "customer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "product" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING(256) NOT NULL,
    "author" STRING(256) NOT NULL,
    "rating" DECIMAL(4,2) NOT NULL,
    "description" STRING(3000) NOT NULL,
    "language" STRING(64) NOT NULL,
    "isbn" STRING(13) NOT NULL,
    "genres" STRING(256) NOT NULL,
    "characters" STRING(1082) NOT NULL,
    "pages" INT4 NOT NULL,
    "published_at" DATE NOT NULL,
    "cover_img" STRING(256) NOT NULL,
    "price" DECIMAL(8,0),

    CONSTRAINT "product_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "total_price" DECIMAL(20,6),
    "payment_method" STRING(20) NOT NULL,
    "created_at" TIMESTAMP(0) NOT NULL,
    "status" STRING(10) NOT NULL,
    "customer_id" STRING(40) NOT NULL,

    CONSTRAINT "transaction_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "transaction_product" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "transaction_id" INT4,
    "product_id" INT4,

    CONSTRAINT "transaction_product_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "_migration_internal_statements_statement_id_key" ON "_migration_internal_statements"("statement_id");

-- CreateIndex
CREATE UNIQUE INDEX "id" ON "customer"("id");

-- CreateIndex
CREATE UNIQUE INDEX "id" ON "product"("id");

-- CreateIndex
CREATE UNIQUE INDEX "id" ON "transaction"("id");

-- CreateIndex
CREATE UNIQUE INDEX "id" ON "transaction_product"("id");
