-- CreateTable
CREATE TABLE "_migration_internal_statements" (
    "statement_order" INT8 NOT NULL,
    "statement_id" UUID NOT NULL,
    "data" JSONB,
    CONSTRAINT "_migration_internal_statements_pkey" PRIMARY KEY ("statement_order")
);
-- CreateTable
CREATE TABLE "customer" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING(255) NOT NULL,
    "address" STRING(255) NOT NULL,
    "email" STRING(50),
    "gender" STRING(20),
    CONSTRAINT "customer_pkey" PRIMARY KEY ("id")
);
-- CreateIndex
CREATE UNIQUE INDEX "_migration_internal_statements_statement_id_key" ON "_migration_internal_statements"("statement_id");
-- CreateIndex
CREATE UNIQUE INDEX "id" ON "customer"("id");